import { Product, StoreInfo, STORE_INFO } from './types';
export { STORE_INFO };

export const PRODUCTS: Product[] = [
  // --- HERO FLAGSHIP IPHONES ---
  {
    id: "iphone-18-pro-max",
    name: "iPhone 18 Pro Max",
    slug: "iphone-18-pro-max",
    brand: "Apple",
    category: "iphones",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 2450000,
    originalPriceNGN: 2600000,
    storage: "512GB",
    batteryHealth: 100,
    colors: ["Titanium Bronze", "Natural Titanium", "Obsidian Black"],
    colorHexes: ["#8C5333", "#D4C7BA", "#1E1E20"],
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=1200&auto=format&fit=crop",
    tagline: "The Pinnacle of Apple Engineering.",
    description: "Next-generation Neural Engine, Aerospace-grade Grade 5 titanium chassis, ProMotion 1-120Hz display with anti-reflective nanotech.",
    isFeatured: true,
    isHero: true,
    warranty: "1 Year International Apple Warranty",
    inStock: true,
    specs: {
      display: "6.9\" Super Retina XDR ProMotion OLED",
      camera: "48MP Quad-Pixel + 5x Optical Periscope Zoom",
      battery: "Up to 33 hours video playback",
      os: "iOS 20",
      warrantyStatus: "Sealed Box • 100% Genuine Guaranteed"
    }
  },
  {
    id: "iphone-16-pro-max-uk",
    name: "iPhone 16 Pro Max",
    slug: "iphone-16-pro-max-uk",
    brand: "Apple",
    category: "iphones",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 1750000,
    originalPriceNGN: 1950000,
    storage: "256GB",
    batteryHealth: 96,
    colors: ["Desert Titanium", "Black Titanium"],
    colorHexes: ["#C5A582", "#212121"],
    imageUrl: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?q=80&w=1200&auto=format&fit=crop",
    tagline: "Pure Titanium. Flawlessly Inspected.",
    description: "Factory Unlocked direct from UK. 96% battery health, zero scratches on frame, FaceID and TrueTone fully tested.",
    isFeatured: true,
    warranty: "30-Day Instant Replacement + 6 Months Store Warranty",
    inStock: true,
    specs: {
      display: "6.9\" Super Retina XDR OLED",
      camera: "48MP Fusion + 48MP Ultra Wide + 5x Telephoto",
      battery: "96% Verified Original Battery",
      os: "iOS 18 / 19 upgradeable",
      warrantyStatus: "Tested with 40-Point Hardware Audit"
    }
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    slug: "iphone-15-pro-max",
    brand: "Apple",
    category: "iphones",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 1320000,
    originalPriceNGN: 1450000,
    storage: "256GB",
    batteryHealth: 92,
    colors: ["Natural Titanium", "Blue Titanium"],
    colorHexes: ["#9F9C96", "#394451"],
    imageUrl: "https://images.unsplash.com/photo-1695048064972-2771239c8112?q=80&w=1200&auto=format&fit=crop",
    tagline: "Titanium Power at Unbeatable Value.",
    description: "A17 Pro chip with hardware ray tracing, USB-C 3.0 speeds. Clean UK open-box condition.",
    isFeatured: true,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.7\" Super Retina XDR OLED 120Hz",
      camera: "48MP Main + 12MP 5x Zoom",
      battery: "92% Clean Original Battery",
      os: "iOS 18",
      warrantyStatus: "Verified Factory Unlocked"
    }
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    slug: "iphone-14-pro",
    brand: "Apple",
    category: "iphones",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 980000,
    originalPriceNGN: 1080000,
    storage: "128GB",
    batteryHealth: 89,
    colors: ["Deep Purple", "Space Black"],
    colorHexes: ["#4E4050", "#1C1C1E"],
    imageUrl: "https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?q=80&w=1200&auto=format&fit=crop",
    tagline: "Dynamic Island Innovator.",
    description: "First generation Dynamic Island, Always-On Display, A16 Bionic speed.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.1\" Super Retina XDR OLED",
      camera: "48MP + 12MP Telephoto",
      battery: "89% Health",
      os: "iOS 18 Supported",
      warrantyStatus: "Hardware 100% Ok"
    }
  },
  {
    id: "iphone-13-pro-max",
    name: "iPhone 13 Pro Max",
    slug: "iphone-13-pro-max",
    brand: "Apple",
    category: "iphones",
    condition: "uk_used_a",
    conditionLabel: "Grade A UK Used",
    priceNGN: 780000,
    originalPriceNGN: 850000,
    storage: "256GB",
    batteryHealth: 88,
    colors: ["Sierra Blue", "Graphite"],
    colorHexes: ["#98B0C4", "#464648"],
    imageUrl: "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?q=80&w=1200&auto=format&fit=crop",
    tagline: "The Battery Life Champion.",
    description: "Legendary battery endurance, ProMotion 120Hz display, triple computational cameras.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.7\" Super Retina XDR OLED 120Hz",
      camera: "Triple 12MP System with Night Mode",
      battery: "88% Health",
      os: "iOS 18 Supported",
      warrantyStatus: "Clean UK Unit"
    }
  },
  {
    id: "iphone-12",
    name: "iPhone 12",
    slug: "iphone-12",
    brand: "Apple",
    category: "iphones",
    condition: "uk_used_a",
    conditionLabel: "Grade A UK Used",
    priceNGN: 420000,
    originalPriceNGN: 460000,
    storage: "128GB",
    batteryHealth: 87,
    colors: ["Pacific Blue", "White"],
    colorHexes: ["#2D4B66", "#F9F6EF"],
    imageUrl: "https://images.unsplash.com/photo-1605236453806-6ff36851218e?q=80&w=1200&auto=format&fit=crop",
    tagline: "Sleek 5G Everyday Driver.",
    description: "Ceramic Shield front, 5G cellular speed, flat-edge aluminum design.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.1\" Super Retina XDR OLED",
      camera: "Dual 12MP Wide/Ultra-Wide",
      battery: "87% Original Battery",
      os: "iOS 17/18 Supported",
      warrantyStatus: "TrueTone & FaceID Active"
    }
  },
  {
    id: "iphone-11",
    name: "iPhone 11",
    slug: "iphone-11",
    brand: "Apple",
    category: "iphones",
    condition: "uk_used_a",
    conditionLabel: "Grade A UK Used",
    priceNGN: 320000,
    originalPriceNGN: 360000,
    storage: "128GB",
    batteryHealth: 86,
    colors: ["Black", "Purple", "Green"],
    colorHexes: ["#1F2020", "#D1CDDA", "#BDE0D0"],
    imageUrl: "https://images.unsplash.com/photo-1574755393849-623942496936?q=80&w=1200&auto=format&fit=crop",
    tagline: "Solid Student & Daily Driver Choice.",
    description: "Exceptional value for campus and business work in Ogbomoso. Clean camera and speaker.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.1\" Liquid Retina HD",
      camera: "Dual 12MP Ultra Wide and Wide",
      battery: "86% Health",
      os: "iOS Supported",
      warrantyStatus: "Factory Unlocked"
    }
  },
  {
    id: "iphone-xr",
    name: "iPhone XR",
    slug: "iphone-xr",
    brand: "Apple",
    category: "iphones",
    condition: "uk_used_a",
    conditionLabel: "Grade A UK Used",
    priceNGN: 240000,
    originalPriceNGN: 270000,
    storage: "64GB",
    batteryHealth: 85,
    colors: ["Coral", "Black", "White"],
    colorHexes: ["#FF6E52", "#212121", "#F5F5F7"],
    imageUrl: "https://images.unsplash.com/photo-1556656793-08538906a9f8?q=80&w=1200&auto=format&fit=crop",
    tagline: "Most Affordable iOS Experience.",
    description: "A12 Bionic processor, Face ID, portrait mode single camera. Affordable entry into the Apple ecosystem.",
    isFeatured: false,
    warranty: "21-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.1\" Liquid Retina Display",
      camera: "12MP Single Sensor",
      battery: "85% Battery Health",
      os: "iOS 16/17 Supported",
      warrantyStatus: "Inspected & Certified Clean"
    }
  },

  // --- SAMSUNG GALAXY FLAGSHIPS ---
  {
    id: "samsung-s26-ultra",
    name: "Samsung Galaxy S26 Ultra 5G",
    slug: "samsung-s26-ultra",
    brand: "Samsung",
    category: "samsung",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 2550000,
    originalPriceNGN: 2750000,
    storage: "1TB",
    batteryHealth: 100,
    colors: ["Titanium Amber", "Phantom Black"],
    colorHexes: ["#8C5333", "#121212"],
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?q=80&w=1200&auto=format&fit=crop",
    tagline: "Ultra Power. Integrated S-Pen Mastery.",
    description: "Brand new sealed in box. 200MP ISOCELL sensor, Snapdragon 8 Gen 5 Extreme, Anti-glare Armor Glass.",
    isFeatured: true,
    warranty: "24-Month Samsung Warranty",
    inStock: true,
    specs: {
      display: "6.8\" Dynamic AMOLED 2X 144Hz 3000 nits",
      camera: "200MP + 50MP Periscope + 50MP Ultra-Wide",
      battery: "5500mAh 65W Fast Charging",
      os: "Android 16 with OneUI 8",
      warrantyStatus: "Sealed Original Pack"
    }
  },
  {
    id: "samsung-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    slug: "samsung-s24-ultra",
    brand: "Samsung",
    category: "samsung",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 1480000,
    originalPriceNGN: 1620000,
    storage: "512GB",
    batteryHealth: 98,
    colors: ["Titanium Gray", "Titanium Violet"],
    colorHexes: ["#79787D", "#544E61"],
    imageUrl: "https://images.unsplash.com/photo-1580910051074-3eb694886505?q=80&w=1200&auto=format&fit=crop",
    tagline: "Galaxy AI Champion in Titanium.",
    description: "Built-in S-Pen, flat display with Gorilla Armor reflection shield, full Galaxy AI circle to search.",
    isFeatured: true,
    warranty: "30-Day Replacement Guarantee",
    inStock: true,
    specs: {
      display: "6.8\" Flat QHD+ AMOLED 120Hz",
      camera: "200MP Quad Tele System",
      battery: "5000mAh",
      os: "Android 14/15 One UI",
      warrantyStatus: "Grade A+ Pristine Condition"
    }
  },
  {
    id: "samsung-s22-ultra",
    name: "Samsung Galaxy S22 Ultra",
    slug: "samsung-s22-ultra",
    brand: "Samsung",
    category: "samsung",
    condition: "uk_used_a",
    conditionLabel: "Grade A UK Used",
    priceNGN: 690000,
    originalPriceNGN: 760000,
    storage: "256GB",
    batteryHealth: 91,
    colors: ["Burgundy", "Phantom Black"],
    colorHexes: ["#5D2E3B", "#171717"],
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=1200&auto=format&fit=crop",
    tagline: "The Modern Note Successor.",
    description: "Deep Burgundy finish, 108MP camera, 100x Space Zoom, built-in stylus.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.8\" Edge QHD+ Dynamic AMOLED 2X",
      camera: "108MP + 10x Periscope",
      battery: "5000mAh",
      os: "Android 14 OneUI 6.1",
      warrantyStatus: "Unlocked Single/Dual SIM"
    }
  },
  {
    id: "samsung-s9-plus",
    name: "Samsung Galaxy S9+",
    slug: "samsung-s9-plus",
    brand: "Samsung",
    category: "samsung",
    condition: "uk_used_a",
    conditionLabel: "Grade A UK Used",
    priceNGN: 1450000,
    originalPriceNGN: 160000,
    storage: "64GB",
    batteryHealth: 88,
    colors: ["Midnight Black", "Coral Blue"],
    colorHexes: ["#1B1B1B", "#386596"],
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=1200&auto=format&fit=crop",
    tagline: "Ultra-Budget Samsung Workhorse.",
    description: "Dual aperture camera, headphone jack, expandable SD card slot. Very clean UK stock.",
    isFeatured: false,
    warranty: "14-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.2\" Quad HD+ Super AMOLED",
      camera: "Dual 12MP Super Speed Dual Pixel",
      battery: "3500mAh",
      os: "Android",
      warrantyStatus: "Clean Glass & Frame"
    }
  },

  // --- GOOGLE PIXEL PHONES ---
  {
    id: "pixel-11-pro-xl",
    name: "Google Pixel 11 Pro XL",
    slug: "pixel-11-pro-xl",
    brand: "Google",
    category: "pixel",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 2150000,
    originalPriceNGN: 2300000,
    storage: "512GB",
    batteryHealth: 100,
    colors: ["Hazel Bronze", "Obsidian"],
    colorHexes: ["#6F513C", "#212121"],
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=1200&auto=format&fit=crop",
    tagline: "Google Tensor G6 with On-Device Super AI.",
    description: "Sealed box unit. Industry-leading computational photography, 7 years of OS updates guaranteed.",
    isFeatured: true,
    warranty: "1 Year International Google Warranty",
    inStock: true,
    specs: {
      display: "6.8\" Super Actua LTPO OLED 1-120Hz",
      camera: "50MP Main + 48MP Ultrawide + 48MP 5x Zoom",
      battery: "5100mAh 45W Fast Charging",
      os: "Stock Android 16",
      warrantyStatus: "Factory Unlocked Brand New"
    }
  },
  {
    id: "pixel-9-pro-xl",
    name: "Google Pixel 9 Pro XL",
    slug: "pixel-9-pro-xl",
    brand: "Google",
    category: "pixel",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 1280000,
    originalPriceNGN: 1400000,
    storage: "256GB",
    batteryHealth: 99,
    colors: ["Porcelain", "Hazel"],
    colorHexes: ["#EDE8E2", "#636965"],
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=1200&auto=format&fit=crop",
    tagline: "Gemini Nano Integrated Powerhouse.",
    description: "UK open-box unit in pristine condition. Tensor G4, polished metal camera visor, incredible night sight.",
    isFeatured: true,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.8\" Super Actua OLED 3000 nits",
      camera: "50MP Triple Camera with 30x Super Res Zoom",
      battery: "99% Verified Original Battery",
      os: "Android 15",
      warrantyStatus: "Pristine Zero Scratch Condition"
    }
  },
  {
    id: "pixel-8-pro",
    name: "Google Pixel 8 Pro",
    slug: "pixel-8-pro",
    brand: "Google",
    category: "pixel",
    condition: "uk_used_a",
    conditionLabel: "Grade A UK Used",
    priceNGN: 680000,
    originalPriceNGN: 760000,
    storage: "128GB",
    batteryHealth: 93,
    colors: ["Bay Blue", "Obsidian"],
    colorHexes: ["#7FAAD0", "#1C1C1E"],
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=1200&auto=format&fit=crop",
    tagline: "Best-in-Class Computational Camera.",
    description: "Temperature sensor, Magic Editor, Best Take photography features. Clean UK import.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "6.7\" LTPO OLED 120Hz",
      camera: "50MP Octa PD + 48MP Quad PD 5x",
      battery: "93% Original Battery",
      os: "Android 15 Upgradeable",
      warrantyStatus: "Unlocked to All Nigerian Networks"
    }
  },

  // --- M-SERIES MACBOOKS ---
  {
    id: "macbook-pro-16-m4-max",
    name: "MacBook Pro 16\" (M4 Max)",
    slug: "macbook-pro-16-m4-max",
    brand: "Apple",
    category: "macbooks",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 4850000,
    originalPriceNGN: 5100000,
    storage: "1TB",
    ram: "36GB Unified Memory",
    processor: "Apple M4 Max (14-core CPU, 32-core GPU)",
    batteryHealth: 100,
    colors: ["Space Black", "Silver"],
    colorHexes: ["#1B1B1D", "#E3E4E5"],
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
    tagline: "Unrivaled Computing Beast for Creators & Engineers.",
    description: "Brand new factory sealed. Liquid Retina XDR with up to 1600 nits peak brightness, 24-hour battery endurance.",
    isFeatured: true,
    isHero: true,
    warranty: "1 Year Apple Global Warranty",
    inStock: true,
    specs: {
      display: "16.2\" Liquid Retina XDR (3456x2234) ProMotion",
      camera: "12MP Center Stage Camera with Desk View",
      battery: "100Wh Lithium-Polymer (Up to 24 hrs)",
      os: "macOS Sequoia",
      warrantyStatus: "Sealed Box • Original 140W MagSafe Charger"
    }
  },
  {
    id: "macbook-pro-14-m3-pro",
    name: "MacBook Pro 14\" (M3 Pro)",
    slug: "macbook-pro-14-m3-pro",
    brand: "Apple",
    category: "macbooks",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 2350000,
    originalPriceNGN: 2550000,
    storage: "512GB",
    ram: "18GB Unified Memory",
    processor: "Apple M3 Pro (11-core CPU, 14-core GPU)",
    batteryHealth: 97,
    colors: ["Space Black", "Silver"],
    colorHexes: ["#232325", "#E1E1E2"],
    imageUrl: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?q=80&w=1200&auto=format&fit=crop",
    tagline: "Pro Performance in a Compact Form Factor.",
    description: "UK used in mint condition. Low battery cycle count (42 cycles), 97% health, original box and MagSafe cable included.",
    isFeatured: true,
    warranty: "60-Day Store Warranty",
    inStock: true,
    specs: {
      display: "14.2\" Liquid Retina XDR 120Hz",
      camera: "1080p FaceTime HD",
      battery: "97% Health (42 Cycle Count)",
      os: "macOS Sequoia",
      warrantyStatus: "Grade A+ Pristine • Tested OK"
    }
  },
  {
    id: "macbook-air-15-m2",
    name: "MacBook Air 15\" (M2)",
    slug: "macbook-air-15-m2",
    brand: "Apple",
    category: "macbooks",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 1390000,
    originalPriceNGN: 1520000,
    storage: "256GB",
    ram: "8GB Unified Memory",
    processor: "Apple M2 (8-core CPU, 10-core GPU)",
    batteryHealth: 95,
    colors: ["Midnight", "Starlight"],
    colorHexes: ["#182333", "#F0E5D3"],
    imageUrl: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=1200&auto=format&fit=crop",
    tagline: "Impossibly Thin with a Big 15-inch Canvas.",
    description: "Fanless silent design, four-speaker sound system with Spatial Audio. Perfect for devs, writers, and students.",
    isFeatured: false,
    warranty: "45-Day Store Warranty",
    inStock: true,
    specs: {
      display: "15.3\" Liquid Retina Display 500 nits",
      camera: "1080p FaceTime HD",
      battery: "95% Battery Health",
      os: "macOS Sequoia",
      warrantyStatus: "UK Direct • Unlocked iCloud"
    }
  },
  {
    id: "macbook-air-13-m1",
    name: "MacBook Air 13\" (M1)",
    slug: "macbook-air-13-m1",
    brand: "Apple",
    category: "macbooks",
    condition: "uk_used_a",
    conditionLabel: "Grade A UK Used",
    priceNGN: 720000,
    originalPriceNGN: 790000,
    storage: "256GB",
    ram: "8GB Unified Memory",
    processor: "Apple M1 Chip",
    batteryHealth: 90,
    colors: ["Space Gray", "Gold"],
    colorHexes: ["#545456", "#E3BEA6"],
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop",
    tagline: "The Legend That Revolutionized Laptops.",
    description: "18-hour battery life, instant wake, silent cooling. The most recommended laptop for university students in Ogbomoso.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "13.3\" Retina Display with TrueTone",
      camera: "720p FaceTime HD",
      battery: "90% Battery Health",
      os: "macOS Sequoia Supported",
      warrantyStatus: "Grade A UK Used • Clean Keyboard"
    }
  },

  // --- WINDOWS LAPTOPS (DELL XPS 2024 - 2026) ---
  {
    id: "dell-xps-16-2026",
    name: "Dell XPS 16 (2026 OLED Edition)",
    slug: "dell-xps-16-2026",
    brand: "Dell",
    category: "laptops",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 3950000,
    originalPriceNGN: 4200000,
    storage: "2TB",
    ram: "64GB LPDDR5X",
    processor: "Intel Core Ultra 9 285H (16-core NPU AI Engine)",
    batteryHealth: 100,
    colors: ["Platinum Silver", "Graphite"],
    colorHexes: ["#DCDDDE", "#28292B"],
    imageUrl: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?q=80&w=1200&auto=format&fit=crop",
    tagline: "Futuristic Minimalist Windows Flagship.",
    description: "Seamless glass touchpad with haptic feedback, capacitive touch function row, 4K+ OLED infinity edge display, NVIDIA RTX 4070 Graphics.",
    isFeatured: true,
    isHero: true,
    warranty: "1 Year Dell Premier On-Site Warranty",
    inStock: true,
    specs: {
      display: "16.3\" 4K+ (3840x2400) OLED Touch 120Hz",
      camera: "1080p FHD RGB-IR with Windows Hello",
      battery: "99.5Wh High-Capacity Cell",
      os: "Windows 11 Pro",
      warrantyStatus: "Factory Sealed with Global Service Tag"
    }
  },
  {
    id: "dell-xps-14-2025",
    name: "Dell XPS 14 (2025 AI PC)",
    slug: "dell-xps-14-2025",
    brand: "Dell",
    category: "laptops",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 2100000,
    originalPriceNGN: 2350000,
    storage: "1TB",
    ram: "32GB LPDDR5X",
    processor: "Intel Core Ultra 7 155H + RTX 4050 6GB",
    batteryHealth: 98,
    colors: ["Graphite Black"],
    colorHexes: ["#232426"],
    imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1200&auto=format&fit=crop",
    tagline: "Engineered Precision for Heavy AI & CAD Workflows.",
    description: "UK open-box unit in immaculate shape. Zero scuffs, crystal clean 3.2K OLED panel, 98% battery design capacity.",
    isFeatured: true,
    warranty: "60-Day Store Warranty",
    inStock: true,
    specs: {
      display: "14.5\" 3.2K (3200x2000) OLED Touch 120Hz",
      camera: "FHD Webcam with Physical Shutter & Windows Hello",
      battery: "98% Health (Under 20 cycles)",
      os: "Windows 11 Pro",
      warrantyStatus: "Tested with Dell Diagnostics (100% Pass)"
    }
  },
  {
    id: "dell-xps-13-2024",
    name: "Dell XPS 13 (2024 Ultra-Portable)",
    slug: "dell-xps-13-2024",
    brand: "Dell",
    category: "laptops",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 1450000,
    originalPriceNGN: 1600000,
    storage: "512GB",
    ram: "16GB LPDDR5X",
    processor: "Intel Core Ultra 7 155H with Intel Arc Graphics",
    batteryHealth: 94,
    colors: ["Platinum Silver"],
    colorHexes: ["#CFD1D3"],
    imageUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1200&auto=format&fit=crop",
    tagline: "Featherlight Portability, Uncompromising Power.",
    description: "Weighs only 1.19kg with edge-to-edge CNC machined aluminum. Stunning battery life and high-speed typing ergonomics.",
    isFeatured: false,
    warranty: "45-Day Store Warranty",
    inStock: true,
    specs: {
      display: "13.4\" FHD+ (1920x1200) InfinityEdge 500 nits",
      camera: "1080p IR Camera",
      battery: "94% Battery Health",
      os: "Windows 11 Home/Pro",
      warrantyStatus: "Grade A+ UK Stock • Direct Dispatch"
    }
  },

  // --- IPAD & TABLETS ---
  {
    id: "ipad-pro-13-m4",
    name: "iPad Pro 13\" (M4 OLED)",
    slug: "ipad-pro-13-m4",
    brand: "Apple",
    category: "ipad",
    productType: "tablets",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 1980000,
    originalPriceNGN: 2150000,
    storage: "256GB",
    batteryHealth: 100,
    colors: ["Space Black", "Silver"],
    colorHexes: ["#1C1C1E", "#E3E4E5"],
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1200&auto=format&fit=crop",
    tagline: "Ultra Retina XDR Tandem OLED Display.",
    description: "Impossibly thin 5.1mm design powered by breakthrough Apple M4 silicon with 38 TOPS Neural Engine.",
    isFeatured: true,
    warranty: "1 Year Apple Warranty",
    inStock: true,
    specs: {
      display: "13\" Tandem OLED (2752x2064) 1000 nits",
      camera: "12MP Wide + LiDAR Scanner",
      battery: "Up to 10 hours web/video",
      os: "iPadOS 18",
      warrantyStatus: "Sealed Pack • Pencil Pro Compatible"
    }
  },
  {
    id: "ipad-air-11-m2",
    name: "iPad Air 11\" (M2)",
    slug: "ipad-air-11-m2",
    brand: "Apple",
    category: "ipad",
    productType: "tablets",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 920000,
    originalPriceNGN: 1050000,
    storage: "128GB",
    batteryHealth: 98,
    colors: ["Space Gray", "Starlight", "Blue"],
    colorHexes: ["#545456", "#EFE5D8", "#C3D4DF"],
    imageUrl: "https://images.unsplash.com/photo-1561154464-82e9adf32764?q=80&w=1200&auto=format&fit=crop",
    tagline: "Fresh Speed. Liquid Retina Canvas.",
    description: "UK open-box unit in immaculate condition. Landscape front camera with Center Stage, M2 multi-core prowess.",
    isFeatured: false,
    warranty: "45-Day Store Warranty",
    inStock: true,
    specs: {
      display: "11\" Liquid Retina Display with P3 Color",
      camera: "12MP Center Stage Camera",
      battery: "98% Health (Clean)",
      os: "iPadOS 18",
      warrantyStatus: "Grade A+ UK Used • iCloud Free"
    }
  },

  // --- AIRPODS & AUDIO ---
  {
    id: "airpods-pro-2-usbc",
    name: "AirPods Pro (2nd Gen, USB-C)",
    slug: "airpods-pro-2-usbc",
    brand: "Apple",
    category: "airpods",
    productType: "audio",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 385000,
    originalPriceNGN: 420000,
    storage: "N/A",
    colors: ["White"],
    colorHexes: ["#FFFFFF"],
    imageUrl: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=1200&auto=format&fit=crop",
    tagline: "Pro-level Active Noise Cancellation & Spatial Audio.",
    description: "H2 chip with Adaptive Audio, Transparency mode, dust/sweat resistance (IP54), and MagSafe USB-C case with speaker.",
    isFeatured: true,
    warranty: "1 Year Apple Warranty",
    inStock: true,
    specs: {
      display: "H2 Apple Headphone Chip",
      battery: "Up to 6 hours listening (30 hrs with case)",
      os: "iOS / Android Compatible",
      warrantyStatus: "Sealed Original Box with Serial Check"
    }
  },
  {
    id: "airpods-max-usbc",
    name: "AirPods Max (USB-C Edition)",
    slug: "airpods-max-usbc",
    brand: "Apple",
    category: "airpods",
    productType: "audio",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 850000,
    originalPriceNGN: 950000,
    storage: "N/A",
    colors: ["Space Black", "Silver"],
    colorHexes: ["#1F1F21", "#E6E6E8"],
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=1200&auto=format&fit=crop",
    tagline: "Computational Audio Perfection with Anodized Aluminum.",
    description: "Clean UK unit with pristine memory foam ear cushions, breathable knit mesh canopy, and lossless USB-C audio.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "Apple H1 Chip in Each Ear Cup",
      battery: "Up to 20 hours with ANC active",
      os: "iOS / macOS / Windows",
      warrantyStatus: "Grade A+ • Tested Hardware & Mic"
    }
  },

  // --- APPLE WATCH ---
  {
    id: "apple-watch-ultra-2",
    name: "Apple Watch Ultra 2 (Titanium 49mm)",
    slug: "apple-watch-ultra-2",
    brand: "Apple",
    category: "iwatch",
    productType: "watches",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 1050000,
    originalPriceNGN: 1200000,
    storage: "64GB",
    batteryHealth: 99,
    colors: ["Natural Titanium"],
    colorHexes: ["#D1CAC2"],
    imageUrl: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?q=80&w=1200&auto=format&fit=crop",
    tagline: "The Most Capable Rugged Adventure Smartwatch.",
    description: "Grade A+ UK stock. 3000 nits brightness, dual-frequency precision GPS, 100m water resistance, 36-hour battery endurance.",
    isFeatured: true,
    warranty: "60-Day Store Warranty",
    inStock: true,
    specs: {
      display: "49mm Always-On Retina Sapphire Crystal",
      battery: "99% Health (Up to 72 hrs in Low Power)",
      os: "watchOS 11",
      warrantyStatus: "Pristine Case & Trail Loop Band"
    }
  },
  {
    id: "apple-watch-series-10",
    name: "Apple Watch Series 10 (46mm)",
    slug: "apple-watch-series-10",
    brand: "Apple",
    category: "iwatch",
    productType: "watches",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 680000,
    originalPriceNGN: 740000,
    storage: "64GB",
    batteryHealth: 100,
    colors: ["Jet Black", "Rose Gold"],
    colorHexes: ["#0C0C0E", "#E6B8B8"],
    imageUrl: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=1200&auto=format&fit=crop",
    tagline: "Apple's Thinnest Smartwatch with Wide-Angle OLED.",
    description: "Brand new sealed. Faster charging (80% in 30 mins), sleep apnea notifications, depth gauge and water temperature sensor.",
    isFeatured: false,
    warranty: "1 Year Apple Warranty",
    inStock: true,
    specs: {
      display: "Wide-Angle OLED Display",
      battery: "18-36 hours battery life",
      os: "watchOS 11",
      warrantyStatus: "Factory Sealed Original Box"
    }
  },

  // --- SAMSUNG GALAXY TAB & WATCH ---
  {
    id: "galaxy-tab-s10-ultra",
    name: "Samsung Galaxy Tab S10 Ultra 5G",
    slug: "galaxy-tab-s10-ultra",
    brand: "Samsung",
    category: "galaxy-tab",
    productType: "tablets",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 1850000,
    originalPriceNGN: 2050000,
    storage: "512GB",
    ram: "12GB",
    batteryHealth: 100,
    colors: ["Moonstone Gray"],
    colorHexes: ["#5D6065"],
    imageUrl: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=1200&auto=format&fit=crop",
    tagline: "Colossal 14.6\" Dynamic AMOLED 2X Canvas with Galaxy AI.",
    description: "Brand new sealed pack. Anti-reflection coating, IP68 water resistance, Bundled S-Pen, MediaTek Dimensity 9300+ powerhouse.",
    isFeatured: true,
    warranty: "1 Year Samsung Warranty",
    inStock: true,
    specs: {
      display: "14.6\" 120Hz Dynamic AMOLED 2X",
      camera: "Dual Rear 13MP+8MP & Dual Front 12MP",
      battery: "11,200mAh 45W Fast Charging",
      os: "Android 14 OneUI 6.1 with DeX",
      warrantyStatus: "Sealed with S-Pen in Box"
    }
  },
  {
    id: "galaxy-watch-ultra",
    name: "Samsung Galaxy Watch Ultra (47mm LTE)",
    slug: "galaxy-watch-ultra",
    brand: "Samsung",
    category: "galaxy-watch",
    productType: "watches",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 750000,
    originalPriceNGN: 850000,
    storage: "32GB",
    batteryHealth: 98,
    colors: ["Titanium Gray", "Titanium White"],
    colorHexes: ["#484B4F", "#EDECE8"],
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200&auto=format&fit=crop",
    tagline: "Built for Extreme Fitness with Dual-Frequency GPS.",
    description: "Clean UK import. Grade 4 Titanium cushion case, 10ATM water resistance, Quick Button, up to 100-hour battery life in power save mode.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "1.5\" Super AMOLED Sapphire Crystal 3000 nits",
      battery: "590mAh cell (98% health)",
      os: "Wear OS Powered by Samsung",
      warrantyStatus: "Grade A+ Condition • Certified Tested"
    }
  },

  // --- GOOGLE PIXEL TABLET, WATCH & BUDS ---
  {
    id: "pixel-tablet-dock",
    name: "Google Pixel Tablet with Speaker Dock",
    slug: "pixel-tablet-dock",
    brand: "Google",
    category: "pixel-tablet",
    productType: "tablets",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 620000,
    originalPriceNGN: 700000,
    storage: "256GB",
    batteryHealth: 96,
    colors: ["Porcelain", "Hazel"],
    colorHexes: ["#EDE8E2", "#636965"],
    imageUrl: "https://images.unsplash.com/photo-1561154464-82e9adf32764?q=80&w=1200&auto=format&fit=crop",
    tagline: "Hub Mode Smart Home Display & High-Performance Tablet.",
    description: "Includes magnetic charging speaker dock. Tensor G2, 11-inch display, quad speakers, seamless Google ecosystem pairing.",
    isFeatured: false,
    warranty: "30-Day Store Warranty",
    inStock: true,
    specs: {
      display: "10.95\" LCD (2560x1600) with USI 2.0 stylus support",
      camera: "8MP Front and Rear with 1080p video",
      battery: "96% Battery Health",
      os: "Stock Android 15",
      warrantyStatus: "Includes Magnetic Speaker Dock"
    }
  },
  {
    id: "pixel-watch-3",
    name: "Google Pixel Watch 3 (45mm LTE)",
    slug: "pixel-watch-3",
    brand: "Google",
    category: "pixel-watch",
    productType: "watches",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 580000,
    originalPriceNGN: 640000,
    storage: "32GB",
    batteryHealth: 100,
    colors: ["Matte Black", "Polished Silver"],
    colorHexes: ["#1B1B1C", "#D2D3D5"],
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200&auto=format&fit=crop",
    tagline: "Bigger Actua Display with Comprehensive Fitbit Health.",
    description: "Brand new sealed. 2000 nits peak brightness, ultra-responsive 1-60Hz refresh rate, advanced readiness & cardio load metrics.",
    isFeatured: false,
    warranty: "1 Year Google Warranty",
    inStock: true,
    specs: {
      display: "45mm Actua AMOLED Display 2000 nits",
      battery: "420mAh (Up to 36 hours in Battery Saver)",
      os: "Wear OS 5",
      warrantyStatus: "Factory Sealed Original Packaging"
    }
  },
  {
    id: "pixel-buds-pro-2",
    name: "Google Pixel Buds Pro 2",
    slug: "pixel-buds-pro-2",
    brand: "Google",
    category: "pixel-buds",
    productType: "audio",
    condition: "brand_new",
    conditionLabel: "Brand New Sealed",
    priceNGN: 320000,
    originalPriceNGN: 360000,
    storage: "N/A",
    colors: ["Hazel", "Porcelain"],
    colorHexes: ["#636965", "#EDE8E2"],
    imageUrl: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=1200&auto=format&fit=crop",
    tagline: "First-ever Tensor A1 Audio Chip with Silent Seal 2.0.",
    description: "Brand new sealed. 2x better active noise cancellation, Gemini Live conversation integration, twist-to-adjust ergonomic fit.",
    isFeatured: false,
    warranty: "1 Year Google Warranty",
    inStock: true,
    specs: {
      display: "Tensor A1 Dedicated Audio Chip",
      battery: "Up to 30 hours with charging case",
      os: "Android & iOS Supported",
      warrantyStatus: "Brand New Sealed Box"
    }
  },

  // --- WINDOWS WORKSTATIONS ---
  {
    id: "thinkpad-x1-carbon-gen12",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    slug: "thinkpad-x1-carbon-gen12",
    brand: "Lenovo",
    category: "laptops",
    productType: "laptops",
    condition: "uk_used_a_plus",
    conditionLabel: "Grade A+ UK Used",
    priceNGN: 1950000,
    originalPriceNGN: 2200000,
    storage: "1TB",
    ram: "32GB LPDDR5X",
    processor: "Intel Core Ultra 7 155H with Intel Arc",
    batteryHealth: 97,
    colors: ["Deep ThinkPad Black"],
    colorHexes: ["#171717"],
    imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=1200&auto=format&fit=crop",
    tagline: "The Gold Standard for Engineers & Business Executives.",
    description: "Legendary carbon fiber durability, Communications Bar with 8MP camera, haptic trackpad, pristine UK corporate import.",
    isFeatured: false,
    warranty: "60-Day Store Warranty",
    inStock: true,
    specs: {
      display: "14\" 2.8K (2880x1800) OLED 120Hz 400 nits",
      camera: "8MP Computer Vision with Windows Hello",
      battery: "57Wh battery (97% health)",
      os: "Windows 11 Pro",
      warrantyStatus: "Clean UK Corporate Lease Return"
    }
  }
];

export const CATEGORIES_CONFIG = [
  { id: 'all', name: 'All Gadgets' },
  { id: 'apple', name: 'Apple Ecosystem' },
  { id: 'iphones', name: 'iPhones (Xr - 18 Pro Max)' },
  { id: 'ipad', name: 'iPads (Pro & Air)' },
  { id: 'macbooks', name: 'M-Series MacBooks' },
  { id: 'airpods', name: 'AirPods & Audio' },
  { id: 'iwatch', name: 'Apple Watch' },
  { id: 'samsung', name: 'Samsung Galaxy' },
  { id: 'galaxy-tab', name: 'Galaxy Tab' },
  { id: 'galaxy-watch', name: 'Galaxy Watch' },
  { id: 'pixel', name: 'Google Pixel' },
  { id: 'pixel-tablet', name: 'Pixel Tablet' },
  { id: 'pixel-watch', name: 'Pixel Watch & Buds' },
  { id: 'laptops', name: 'Dell XPS & Workstations' },
];

export const STORAGE_OPTIONS = ['64GB', '128GB', '256GB', '512GB', '1TB', '2TB'];

export const CONDITION_OPTIONS = [
  { id: 'all', label: 'All Conditions' },
  { id: 'brand_new', label: 'Brand New Sealed' },
  { id: 'uk_used_a_plus', label: 'Grade A+ UK Used' },
  { id: 'uk_used_a', label: 'Grade A UK Used' },
];
